services:
  app:
    build: .
    container_name: recipes-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recipes
      - JWT_SECRET=superSecretTokenKey123
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: recipes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
